# Exploratory Data Analysis (EDA)

This notebook will focus on exploring tabular data through DataFrames. This will only work if you've downloaded the data already.

**Note:** If you didn't use [Anaconda](https://anaconda.com), you may need to do `%pip install` on any missing libraries.

## DataFrames
Now that we have our data, let's load up a table into a DataFrame

In [1]:
import pandas as pd

df_teams = pd.read_csv('../Data/team_info.csv')
df_teams

,team_id,franchiseId,shortName,teamName,abbreviation,link
0,1,23,New Jersey,Devils,NJD,/api/v1/teams/1
1,4,16,Philadelphia,Flyers,PHI,/api/v1/teams/4
2,26,14,Los Angeles,Kings,LAK,/api/v1/teams/26
3,14,31,Tampa Bay,Lightning,TBL,/api/v1/teams/14
4,6,6,Boston,Bruins,BOS,/api/v1/teams/6
5,3,10,NY Rangers,Rangers,NYR,/api/v1/teams/3
6,5,17,Pittsburgh,Penguins,PIT,/api/v1/teams/5
7,17,12,Detroit,Red Wings,DET,/api/v1/teams/17
8,28,29,San Jose,Sharks,SJS,/api/v1/teams/28
9,18,34,Nashville,Predators,NSH,/api/v1/teams/18
10,23,20,Vancouver,Canucks,VAN,/api/v1/teams/23
11,16,11,Chicago,Blackhawks,CHI,/api/v1/teams/16
12,9,30,Ottawa,Senators,OTT,/api/v1/teams/9
13,8,1,Montreal,Canadiens,MTL,/api/v1/teams/8
14,30,37,Minnesota,Wild,MIN,/api/v1/teams/30
15,15,24,Washington,Capitals,WSH,/api/v1/teams/15
16,19,18,St Louis,Blues,STL,/api/v1/teams/19
17,24,32,Anaheim,Ducks,ANA,/api/v1/teams/24
18,27,28,Phoenix,Coyotes,PHX,/api/v1/teams/27
19,2,22,NY Islanders,Islanders,NYI,/api/v1/teams/2
20,10,5,Toronto,Maple Leafs,TOR,/api/v1/teams/10
21,13,33,Florida,Panthers,FLA,/api/v1/teams/13
22,7,19,Buffalo,Sabres,BUF,/api/v1/teams/7
23,20,21,Calgary,Flames,CGY,/api/v1/teams/20
24,21,27,Colorado,Avalanche,COL,/api/v1/teams/21
25,25,15,Dallas,Stars,DAL,/api/v1/teams/25
26,29,36,Columbus,Blue Jackets,CBJ,/api/v1/teams/29
27,52,35,Winnipeg,Jets,WPG,/api/v1/teams/52
28,22,25,Edmonton,Oilers,EDM,/api/v1/teams/22
29,54,38,Vegas,Golden Knights,VGK,/api/v1/teams/54
30,12,26,Carolina,Hurricanes,CAR,/api/v1/teams/12
31,53,28,Arizona,Coyotes,ARI,/api/v1/teams/53
32,11,35,Atlanta,Thrashers,ATL,/api/v1/teams/11

That's a lot. Let's look at just 5 rows

In [2]:
df_teams.head()

,team_id,franchiseId,shortName,teamName,abbreviation,link
0,1,23,New Jersey,Devils,NJD,/api/v1/teams/1
1,4,16,Philadelphia,Flyers,PHI,/api/v1/teams/4
2,26,14,Los Angeles,Kings,LAK,/api/v1/teams/26
3,14,31,Tampa Bay,Lightning,TBL,/api/v1/teams/14
4,6,6,Boston,Bruins,BOS,/api/v1/teams/6

Interesting, but not immediately useful. Let's load up more data from another table.

![Other Tables](../Data/table_relationships.jpeg)

In [3]:
df_team_stats = pd.read_csv('../Data/game_teams_stats.csv')
df_team_stats.head()

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide
0,2018020001,8,away,False,OT,Claude Julien,2.0,36.0,34.0,6.0,4.0,1.0,41.3,10.0,5.0,16.0,left
1,2018020001,10,home,True,OT,Mike Babcock,3.0,26.0,18.0,8.0,3.0,1.0,58.7,21.0,5.0,24.0,left
2,2018020002,6,away,False,REG,Bruce Cassidy,0.0,25.0,28.0,32.0,2.0,0.0,68.3,3.0,5.0,12.0,left
3,2018020002,15,home,True,REG,Todd Reirden,7.0,37.0,16.0,14.0,6.0,4.0,31.7,10.0,13.0,15.0,left
4,2018020003,20,away,False,REG,Bill Peters,2.0,35.0,17.0,7.0,7.0,0.0,57.6,6.0,1.0,6.0,left

In [4]:
df_team_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5440 entries, 0 to 5439
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 5440 non-null   int64
 1   team_id                 5440 non-null   int64
 2   HoA                     5440 non-null   object
 3   won                     5440 non-null   bool
 4   settled_in              5440 non-null   object
 5   head_coach              5440 non-null   object
 6   goals                   5440 non-null   float64
 7   shots                   5440 non-null   float64
 8   hits                    5440 non-null   float64
 9   pim                     5440 non-null   float64
 10  powerPlayOpportunities  5440 non-null   float64
 11  powerPlayGoals          5440 non-null   float64
 12  faceOffWinPercentage    5440 non-null   float64
 13  giveaways               5440 non-null   float64
 14  takeaways               5440 non-null   float64
 15  blocked                 5440 non-null   float64
 16  startRinkSide           5256 non-null   object
dtypes: bool(1), float64(10), int64(2), object(4)
memory usage: 685.4+ KB

## Getting Column Values & Unique Values

In [5]:
df_team_stats["settled_in"]

0        OT
1        OT
2       REG
3       REG
4       REG
       ...
5435    REG
5436    REG
5437    REG
5438    REG
5439    REG
Name: settled_in, Length: 5440, dtype: object

In [6]:
df_team_stats["settled_in"].unique()

array(['OT', 'REG', 'tbc'], dtype=object)

## Descriptive Statistics for Columns and DataFrames

In [7]:
df_team_stats["hits"].describe()

count    5440.000000
mean       23.012868
std         8.363645
min         0.000000
25%        17.000000
50%        22.000000
75%        28.000000
max        80.000000
Name: hits, dtype: float64

In [8]:
df_team_stats.describe()

,game_id,team_id,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked
count,5.440000e+03,5440.000000,5440.000000,5440.000000,5440.000000,5440.000000,5440.000000,5440.000000,5440.000000,5440.00000,5440.000000,5440.000000
mean,2.018021e+09,19.049265,2.973529,31.431250,23.012868,8.326471,2.926838,0.579044,50.000000,10.37500,7.784559,14.353309
std,2.484049e+03,14.018549,1.744067,6.915005,8.363645,6.028738,1.435048,0.749335,7.206157,5.26103,4.230087,4.881138
min,2.018020e+09,1.000000,0.000000,13.000000,0.000000,0.000000,0.000000,0.000000,25.900000,0.00000,0.000000,0.000000
25%,2.018020e+09,8.000000,2.000000,26.000000,17.000000,4.000000,2.000000,0.000000,45.100000,6.00000,5.000000,11.000000
50%,2.018021e+09,17.000000,3.000000,31.000000,22.000000,6.000000,3.000000,0.000000,50.000000,10.00000,7.000000,14.000000
75%,2.018021e+09,25.000000,4.000000,36.000000,28.000000,10.000000,4.000000,1.000000,54.900000,14.00000,10.000000,17.000000
max,2.018041e+09,89.000000,10.000000,59.000000,80.000000,60.000000,10.000000,4.000000,74.100000,33.00000,31.000000,36.000000

## Adding a Column

In [9]:
df_team_stats['is_home'] = df_team_stats['HoA'].eq('home')
df_team_stats["has_many_hits"] = df_team_stats["hits"] > 30
df_team_stats.sample(10)

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide,is_home,has_many_hits
3716,2018020927,2,away,False,REG,Barry Trotz,2.0,19.0,31.0,10.0,2.0,0.0,43.5,13.0,3.0,20.0,left,False,True
528,2018020132,14,away,True,REG,Jon Cooper,1.0,24.0,19.0,13.0,3.0,1.0,46.9,1.0,5.0,8.0,left,False,False
914,2018020232,2,away,False,REG,Barry Trotz,2.0,37.0,24.0,8.0,5.0,0.0,42.3,8.0,7.0,12.0,right,False,False
3846,2018020960,19,away,False,OT,Craig Berube,1.0,28.0,21.0,6.0,2.0,1.0,46.3,5.0,6.0,12.0,left,False,False
3772,2018020944,52,away,True,REG,Paul Maurice,6.0,29.0,24.0,6.0,4.0,2.0,44.1,6.0,7.0,18.0,NaN,False,False
3212,2018020802,6,away,True,REG,Bruce Cassidy,1.0,39.0,27.0,6.0,3.0,0.0,63.5,14.0,12.0,15.0,left,False,False
644,2018020159,3,away,False,REG,David Quinn,3.0,25.0,20.0,13.0,3.0,0.0,47.5,10.0,3.0,19.0,left,False,False
2797,2018020700,29,home,True,REG,John Tortorella,7.0,40.0,9.0,6.0,5.0,0.0,69.1,4.0,3.0,12.0,right,True,False
3552,2018020886,23,away,True,OT,Travis Green,3.0,27.0,20.0,6.0,2.0,1.0,61.4,5.0,1.0,11.0,left,False,False
265,2018020063,14,home,True,REG,Jon Cooper,8.0,31.0,22.0,12.0,7.0,4.0,48.3,10.0,11.0,12.0,right,True,False

In [10]:
df_team_stats['wins'] = df_team_stats['won'].apply(lambda x: 1 if x else 0)
df_team_stats['games'] = 1
df_team_stats

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,...,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide,is_home,has_many_hits,wins,games
0,2018020001,8,away,False,OT,Claude Julien,2.0,36.0,34.0,6.0,...,1.0,41.3,10.0,5.0,16.0,left,False,True,0,1
1,2018020001,10,home,True,OT,Mike Babcock,3.0,26.0,18.0,8.0,...,1.0,58.7,21.0,5.0,24.0,left,True,False,1,1
2,2018020002,6,away,False,REG,Bruce Cassidy,0.0,25.0,28.0,32.0,...,0.0,68.3,3.0,5.0,12.0,left,False,False,0,1
3,2018020002,15,home,True,REG,Todd Reirden,7.0,37.0,16.0,14.0,...,4.0,31.7,10.0,13.0,15.0,left,True,False,1,1
4,2018020003,20,away,False,REG,Bill Peters,2.0,35.0,17.0,7.0,...,0.0,57.6,6.0,1.0,6.0,left,False,False,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5435,2018030416,19,home,False,REG,Craig Berube,1.0,29.0,29.0,20.0,...,0.0,58.7,12.0,11.0,9.0,right,True,False,0,1
5436,2018030417,19,away,True,REG,Craig Berube,4.0,20.0,36.0,2.0,...,0.0,49.0,7.0,8.0,21.0,right,False,True,1,1
5437,2018030417,6,home,False,REG,Bruce Cassidy,1.0,33.0,28.0,0.0,...,0.0,51.0,13.0,6.0,7.0,right,True,False,0,1
5438,2018030417,19,away,True,REG,Craig Berube,4.0,20.0,36.0,2.0,...,0.0,49.0,7.0,8.0,21.0,right,False,True,1,1
5439,2018030417,6,home,False,REG,Bruce Cassidy,1.0,33.0,28.0,0.0,...,0.0,51.0,13.0,6.0,7.0,right,True,False,0,1

## Merging DataFrames

In [11]:
df_teams_merged = pd.merge(df_team_stats, df_teams, on='team_id')
df_teams_merged.sample(5)

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,...,startRinkSide,is_home,has_many_hits,wins,games,franchiseId,shortName,teamName,abbreviation,link
3479,2018021086,19,away,False,REG,Craig Berube,0.0,35.0,22.0,6.0,...,right,False,False,0,1,18,St Louis,Blues,STL,/api/v1/teams/19
2337,2018020087,3,away,False,OT,David Quinn,3.0,32.0,14.0,8.0,...,left,False,False,0,1,10,NY Rangers,Rangers,NYR,/api/v1/teams/3
2850,2018020262,29,away,True,REG,John Tortorella,2.0,28.0,15.0,15.0,...,left,False,False,1,1,36,Columbus,Blue Jackets,CBJ,/api/v1/teams/29
3984,2018020603,30,home,False,REG,Bruce Boudreau,2.0,33.0,29.0,4.0,...,left,True,False,0,1,37,Minnesota,Wild,MIN,/api/v1/teams/30
4858,2018020710,22,home,True,REG,Ken Hitchcock,7.0,25.0,25.0,8.0,...,right,True,False,1,1,25,Edmonton,Oilers,EDM,/api/v1/teams/22

## Filtering DataFrames

In [12]:
df_rangers = df_teams_merged[df_teams_merged['teamName'].eq('Rangers')]
df_rangers.head()

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,...,startRinkSide,is_home,has_many_hits,wins,games,franchiseId,shortName,teamName,abbreviation,link
2324,2018020006,3,home,False,REG,David Quinn,2.0,36.0,24.0,6.0,...,left,True,False,0,1,10,NY Rangers,Rangers,NYR,/api/v1/teams/3
2325,2018020006,3,home,False,REG,David Quinn,2.0,36.0,24.0,6.0,...,left,True,False,0,1,10,NY Rangers,Rangers,NYR,/api/v1/teams/3
2326,2018020017,3,away,False,REG,David Quinn,1.0,44.0,18.0,17.0,...,right,False,False,0,1,10,NY Rangers,Rangers,NYR,/api/v1/teams/3
2327,2018020017,3,away,False,REG,David Quinn,1.0,44.0,18.0,17.0,...,right,False,False,0,1,10,NY Rangers,Rangers,NYR,/api/v1/teams/3
2328,2018020029,3,away,False,REG,David Quinn,5.0,24.0,27.0,12.0,...,left,False,False,0,1,10,NY Rangers,Rangers,NYR,/api/v1/teams/3

In [13]:
df_teams_merged[df_teams_merged['giveaways'].gt(30)].sample(5)

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,...,startRinkSide,is_home,has_many_hits,wins,games,franchiseId,shortName,teamName,abbreviation,link
887,2018021201,20,home,True,REG,Bill Peters,6.0,37.0,14.0,2.0,...,left,True,False,1,1,21,Calgary,Flames,CGY,/api/v1/teams/20
824,2018020704,20,home,True,REG,Bill Peters,7.0,26.0,19.0,6.0,...,left,True,False,1,1,21,Calgary,Flames,CGY,/api/v1/teams/20
825,2018020704,20,home,True,REG,Bill Peters,7.0,26.0,19.0,6.0,...,left,True,False,1,1,21,Calgary,Flames,CGY,/api/v1/teams/20
886,2018021201,20,home,True,REG,Bill Peters,6.0,37.0,14.0,2.0,...,left,True,False,1,1,21,Calgary,Flames,CGY,/api/v1/teams/20
863,2018021018,20,home,False,REG,Bill Peters,2.0,37.0,15.0,4.0,...,left,True,False,0,1,21,Calgary,Flames,CGY,/api/v1/teams/20

## Column Listing and Manipulation

In [14]:
df_rangers.columns

Index(['game_id', 'team_id', 'HoA', 'won', 'settled_in', 'head_coach', 'goals',
       'shots', 'hits', 'pim', 'powerPlayOpportunities', 'powerPlayGoals',
       'faceOffWinPercentage', 'giveaways', 'takeaways', 'blocked',
       'startRinkSide', 'is_home', 'has_many_hits', 'wins', 'games',
       'franchiseId', 'shortName', 'teamName', 'abbreviation', 'link'],
      dtype='object')

In [15]:
df_subset = df_teams_merged[["wins", 'games', "head_coach", "goals", "shots", "hits", "pim", "giveaways", "takeaways", "blocked"]]
#df_subset = df_subset.drop(columns=["HoA", "settled_in", "startRinkSide"])

## Grouping

In [16]:
df_grouped = df_subset.groupby('head_coach').agg(['mean', 'sum']).sort_values(('wins','mean'), ascending=False)
df_grouped

                       wins      games          goals             shots  \
                       mean  sum  mean  sum      mean    sum       mean
head_coach
Jon Cooper         0.720930  124   1.0  172  3.802326  654.0  31.825581
Craig Berube       0.606742  108   1.0  178  2.955056  526.0  31.561798
Bruce Cassidy      0.603774  128   1.0  212  3.169811  672.0  32.669811
Bill Peters        0.586207  102   1.0  174  3.448276  600.0  32.413793
Barry Trotz        0.577778  104   1.0  180  2.688889  484.0  28.944444
John Tortorella    0.576087  106   1.0  184  3.108696  572.0  31.652174
Todd Reirden       0.573034  102   1.0  178  3.303371  588.0  30.134831
Peter Laviolette   0.556818   98   1.0  176  2.818182  496.0  32.909091
Paul Maurice       0.556818   98   1.0  176  3.250000  572.0  31.022727
Rod Brind'Amour    0.556701  108   1.0  194  2.907216  564.0  33.804124
Mike Babcock       0.550562   98   1.0  178  3.404494  606.0  33.258427
Peter DeBoer       0.549020  112   1.0  204  3.401961  694.0  32.470588
Bob Murray         0.538462   28   1.0   52  2.769231  144.0  28.192308
Claude Julien      0.536585   88   1.0  164  3.000000  492.0  34.097561
Jim Montgomery     0.526316  100   1.0  190  2.568421  488.0  30.789474
Gerard Gallant     0.516854   92   1.0  178  3.044944  542.0  34.370787
Mike Sullivan      0.511628   88   1.0  172  3.220930  554.0  33.337209
Scott Gordon       0.490196   50   1.0  102  2.921569  298.0  31.490196
Jared Bednar       0.478723   90   1.0  188  3.117021  586.0  32.691489
Rick Tocchet       0.475610   78   1.0  164  2.548780  418.0  30.743902
Jeremy Colliton    0.467742   58   1.0  124  3.451613  428.0  32.532258
Bruce Boudreau     0.451220   74   1.0  164  2.560976  420.0  31.304878
Todd McLellan      0.450000   18   1.0   40  2.850000  114.0  31.500000
Bob Boughner       0.439024   72   1.0  164  3.219512  528.0  32.987805
Travis Green       0.426829   70   1.0  164  2.670732  438.0  29.670732
Ken Hitchcock      0.419355   52   1.0  124  2.774194  344.0  28.419355
Phil Housley       0.402439   66   1.0  164  2.695122  442.0  32.890244
Joel Quenneville   0.400000   12   1.0   30  3.066667   92.0  32.800000
Willie Desjardins  0.391304   54   1.0  138  2.478261  342.0  28.797101
Jeff Blashill      0.390244   64   1.0  164  2.731707  448.0  29.195122
David Quinn        0.390244   64   1.0  164  2.695122  442.0  29.182927
Marc Crawford      0.388889   14   1.0   36  2.833333  102.0  28.277778
Dave Hakstol       0.387097   24   1.0   62  2.967742  184.0  31.516129
John Hynes         0.378049   62   1.0  164  2.670732  438.0  30.341463
Randy Carlyle      0.375000   42   1.0  112  2.214286  248.0  27.464286
Mike Yeo           0.368421   14   1.0   38  2.947368  112.0  30.368421
Guy Boucher        0.343750   44   1.0  128  2.984375  382.0  30.000000
John Stevens       0.307692    8   1.0   26  2.153846   56.0  28.538462
Eddie Oatman       0.200000    2   1.0   10  1.400000   14.0  32.000000

                                hits                pim          giveaways  \
                      sum       mean     sum       mean     sum       mean
head_coach
Jon Cooper         5474.0  26.279070  4520.0   9.709302  1670.0   8.604651
Craig Berube       5618.0  23.134831  4118.0   7.494382  1334.0   8.337079
Bruce Cassidy      6926.0  24.688679  5234.0   8.971698  1902.0   9.650943
Bill Peters        5640.0  16.252874  2828.0   9.045977  1574.0  14.459770
Barry Trotz        5210.0  26.233333  4722.0   7.844444  1412.0  11.988889
John Tortorella    5824.0  22.989130  4230.0   6.467391  1190.0   7.358696
Todd Reirden       5364.0  24.235955  4314.0   8.977528  1598.0  11.730337
Peter Laviolette   5792.0  18.715909  3294.0   8.386364  1476.0  10.681818
Paul Maurice       5460.0  22.727273  4000.0   9.102273  1602.0   9.090909
Rod Brind'Amour    6558.0  26.742268  5188.0   7.680412  1490.0  11.010309
Mike Babcock       5920.0  18.764045  3340.0   6.157303  1096.0  12.247191
Peter DeBoer       6624.0  21.539216  4394.0   9.647059  1968.0   9.813725
Bob Murray         1466.0  24.076923  1252.0  10.000000   520.0  11.230769
Claude Julien      5592.0  26.865854  4406.0   8.317073  1364.0  12.573171
Jim Montgomery     5850.0  22.747368  4322.0   7.652632  1454.0  12.389474
Gerard Gallant     6118.0  29.146067  5188.0   7.808989  1390.0   9.067416
Mike Sullivan      5734.0  29.465116  5068.0   8.290698  1426.0  10.453488
Scott Gordon       3212.0  20.411765  2082.0   8.176471   834.0  10.901961
Jared Bednar       6146.0  21.861702  4110.0   9.489362  1784.0   7.585106
Rick Tocchet       5042.0  24.731707  4056.0   7.060976  1158.0   8.621951
Jeremy Colliton    4034.0  16.709677  2072.0   7.193548   892.0  10.354839
Bruce Boudreau     5134.0  19.536585  3204.0   8.000000  1312.0   6.304878
Todd McLellan      1260.0  23.800000   952.0  10.600000   424.0  12.000000
Bob Boughner       5410.0  23.182927  3802.0   8.390244  1376.0  15.048780
Travis Green       4866.0  21.939024  3598.0   8.792683  1442.0   7.426829
Ken Hitchcock      3524.0  27.677419  3432.0   8.741935  1084.0  11.741935
Phil Housley       5394.0  19.085366  3130.0   6.951220  1140.0   9.378049
Joel Quenneville    984.0  14.133333   424.0   8.933333   268.0   7.800000
Willie Desjardins  3974.0  23.246377  3208.0   7.884058  1088.0  10.144928
Jeff Blashill      4788.0  21.329268  3498.0   7.914634  1298.0  12.500000
David Quinn        4786.0  25.951220  4256.0  10.414634  1708.0  12.670732
Marc Crawford      1018.0  23.222222   836.0   7.055556   254.0  13.055556
Dave Hakstol       1954.0  23.032258  1428.0  10.129032   628.0   8.548387
John Hynes         4976.0  23.463415  3848.0   9.085366  1490.0   9.085366
Randy Carlyle      3076.0  22.750000  2548.0   8.500000   952.0  11.392857
Mike Yeo           1154.0  19.736842   750.0   7.578947   288.0   6.578947
Guy Boucher        3840.0  21.312500  2728.0   8.843750  1132.0  11.609375
John Stevens        742.0  23.307692   606.0   9.153846   238.0  12.076923
Eddie Oatman        320.0  20.400000   204.0   4.000000    40.0   7.600000

                           takeaways            blocked
                      sum       mean     sum       mean     sum
head_coach
Jon Cooper         1480.0   6.883721  1184.0  13.651163  2348.0
Craig Berube       1484.0   8.898876  1584.0  13.370787  2380.0
Bruce Cassidy      2046.0   8.500000  1802.0  13.207547  2800.0
Bill Peters        2516.0  10.459770  1820.0  12.931034  2250.0
Barry Trotz        2158.0   6.811111  1226.0  15.944444  2870.0
John Tortorella    1354.0   7.706522  1418.0  13.532609  2490.0
Todd Reirden       2088.0   8.460674  1506.0  15.168539  2700.0
Peter Laviolette   1880.0   7.431818  1308.0  13.613636  2396.0
Paul Maurice       1600.0   7.613636  1340.0  14.409091  2536.0
Rod Brind'Amour    2136.0  10.659794  2068.0  12.835052  2490.0
Mike Babcock       2180.0   8.662921  1542.0  13.449438  2394.0
Peter DeBoer       2002.0   9.274510  1892.0  13.803922  2816.0
Bob Murray          584.0   8.115385   422.0  15.153846   788.0
Claude Julien      2062.0   7.378049  1210.0  14.268293  2340.0
Jim Montgomery     2354.0   7.147368  1358.0  16.210526  3080.0
Gerard Gallant     1614.0  11.157303  1986.0  14.314607  2548.0
Mike Sullivan      1798.0   7.616279  1310.0  14.965116  2574.0
Scott Gordon       1112.0   6.313725   644.0  16.490196  1682.0
Jared Bednar       1426.0   6.946809  1306.0  16.489362  3100.0
Rick Tocchet       1414.0   7.097561  1164.0  15.829268  2596.0
Jeremy Colliton    1284.0   7.725806   958.0  13.645161  1692.0
Bruce Boudreau     1034.0   6.926829  1136.0  14.890244  2442.0
Todd McLellan       480.0   9.050000   362.0  14.600000   584.0
Bob Boughner       2468.0   9.134146  1498.0  13.878049  2276.0
Travis Green       1218.0   6.524390  1070.0  15.036585  2466.0
Ken Hitchcock      1456.0   7.806452   968.0  14.225806  1764.0
Phil Housley       1538.0   6.134146  1006.0  12.231707  2006.0
Joel Quenneville    234.0   7.200000   216.0  13.800000   414.0
Willie Desjardins  1400.0   5.507246   760.0  14.420290  1990.0
Jeff Blashill      2050.0   5.768293   946.0  13.451220  2206.0
David Quinn        2078.0   8.134146  1334.0  14.792683  2426.0
Marc Crawford       470.0   7.944444   286.0  15.833333   570.0
Dave Hakstol        530.0   5.419355   336.0  14.064516   872.0
John Hynes         1490.0   7.682927  1260.0  14.121951  2316.0
Randy Carlyle      1276.0   6.303571   706.0  14.321429  1604.0
Mike Yeo            250.0   7.473684   284.0  15.842105   602.0
Guy Boucher        1486.0   7.265625   930.0  17.125000  2192.0
John Stevens        314.0   3.692308    96.0  13.461538   350.0
Eddie Oatman         76.0   6.000000    60.0  12.400000   124.0

In [17]:
df_grouped.sort_values(('wins', 'sum'), ascending=False).head(10)

                     wins      games          goals             shots          \
                     mean  sum  mean  sum      mean    sum       mean     sum
head_coach
Bruce Cassidy    0.603774  128   1.0  212  3.169811  672.0  32.669811  6926.0
Jon Cooper       0.720930  124   1.0  172  3.802326  654.0  31.825581  5474.0
Peter DeBoer     0.549020  112   1.0  204  3.401961  694.0  32.470588  6624.0
Craig Berube     0.606742  108   1.0  178  2.955056  526.0  31.561798  5618.0
Rod Brind'Amour  0.556701  108   1.0  194  2.907216  564.0  33.804124  6558.0
John Tortorella  0.576087  106   1.0  184  3.108696  572.0  31.652174  5824.0
Barry Trotz      0.577778  104   1.0  180  2.688889  484.0  28.944444  5210.0
Bill Peters      0.586207  102   1.0  174  3.448276  600.0  32.413793  5640.0
Todd Reirden     0.573034  102   1.0  178  3.303371  588.0  30.134831  5364.0
Jim Montgomery   0.526316  100   1.0  190  2.568421  488.0  30.789474  5850.0

                      hits               pim          giveaways          \
                      mean     sum      mean     sum       mean     sum
head_coach
Bruce Cassidy    24.688679  5234.0  8.971698  1902.0   9.650943  2046.0
Jon Cooper       26.279070  4520.0  9.709302  1670.0   8.604651  1480.0
Peter DeBoer     21.539216  4394.0  9.647059  1968.0   9.813725  2002.0
Craig Berube     23.134831  4118.0  7.494382  1334.0   8.337079  1484.0
Rod Brind'Amour  26.742268  5188.0  7.680412  1490.0  11.010309  2136.0
John Tortorella  22.989130  4230.0  6.467391  1190.0   7.358696  1354.0
Barry Trotz      26.233333  4722.0  7.844444  1412.0  11.988889  2158.0
Bill Peters      16.252874  2828.0  9.045977  1574.0  14.459770  2516.0
Todd Reirden     24.235955  4314.0  8.977528  1598.0  11.730337  2088.0
Jim Montgomery   22.747368  4322.0  7.652632  1454.0  12.389474  2354.0

                 takeaways            blocked
                      mean     sum       mean     sum
head_coach
Bruce Cassidy     8.500000  1802.0  13.207547  2800.0
Jon Cooper        6.883721  1184.0  13.651163  2348.0
Peter DeBoer      9.274510  1892.0  13.803922  2816.0
Craig Berube      8.898876  1584.0  13.370787  2380.0
Rod Brind'Amour  10.659794  2068.0  12.835052  2490.0
John Tortorella   7.706522  1418.0  13.532609  2490.0
Barry Trotz       6.811111  1226.0  15.944444  2870.0
Bill Peters      10.459770  1820.0  12.931034  2250.0
Todd Reirden      8.460674  1506.0  15.168539  2700.0
Jim Montgomery    7.147368  1358.0  16.210526  3080.0